name: e_livre
version: 1.0.3
repository: https://github.com/KaiqueFarias09/eLivre
description: >-
  Provides a simple way to extract information for ebook files 
  such as epub 2.0 and epub 3.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.7

dependencies:
  archive: ^3.4.10
  collection: ^1.15.0
  path: ^1.8.0
  xml: ^6.4.2
