name: liber_epub
description: A package to get information from Epub files
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.7

dependencies:
  archive: ^3.4.10
  path: ^1.9.0
  xml: ^6.4.2
